# Generated by Django 2.2.4 on 2020-02-15 01:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('alpha', 'alpha'), ('alpha', 'alpha'), ('alpha', 'alpha')], default='', max_length=17),
        ),
    ]
