# Generated by Django 2.2.4 on 2020-02-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='skills',
        ),
        migrations.AddField(
            model_name='profiles',
            name='skil',
            field=models.ManyToManyField(to='profiles.Skills'),
        ),
    ]
