# Generated by Django 2.2.4 on 2020-02-15 03:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200215_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('alpha', 'alpha'), ('alpha', 'alpha'), ('alpha', 'alpha')], default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
