# Generated by Django 2.2.4 on 2020-02-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profiles_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='skil',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='skill',
        ),
    ]
