# Generated by Django 2.2.4 on 2020-02-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200215_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.Skills'),
        ),
    ]
