# Generated by Django 2.2.4 on 2020-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200215_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='skills',
            field=models.ManyToManyField(to='profiles.Skills'),
        ),
    ]
