# Generated by Django 2.2.4 on 2020-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200215_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
