# Generated by Django 3.0.3 on 2020-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200215_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
