# Generated by Django 3.0.3 on 2020-02-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200215_1353'),
        ('accounts', '0003_appoint_message'),
    ]

    operations = [
    ]
