# Generated by Django 3.0.3 on 2020-02-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20200215_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/img/')),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('skills', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
