# Generated by Django 3.0.3 on 2020-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/rose2.jpg', upload_to='images/'),
        ),
    ]
